x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    build: .
    platform: linux/amd64
    image: judge0/custom:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    command: bash -c "rails db:migrate && rails server"
    ports:
      - '2358:2358'
    env_file: judge0.conf
    <<: *default-logging
    restart: always

  worker:
    build: .
    platform: linux/amd64
    image: judge0/custom:latest
    command: ['./scripts/workers']
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    env_file: judge0.conf
    <<: *default-logging
    restart: always
